### ISSUE TITLE
Error code  0x10100009

### ISSUE THREAD

**Issue by HirotoGenesis** [guided-hacking/GuidedHacking-Injector#4] opened 2020-06-22 17:52 UTC
When i try to inject a dll file to Black Ops 2, appear error, they tell me to open the Gh_In_Log, and appear this error, how can i fix it, i aprecciate your help ^^, se yah

**Comment by GH-Rake** [comment] 2020-06-22 21:22
#define SR_NTCTE_ERR_TIMEOUT	0x10100009	//WaitForSingleObject

Set your GH injector back to defaults by clicking the button, then try to inject again.

If your DLL is poorly coded, it may not inject.  If you have loader lock in DllMain it won't work.  Make sure your code is perfect.

Sometimes if you import weird libraries it will fail to inject.

It is also possible that anticheat is causing this, I am not familiar with the game.

Try injecting with Extreme Injector, if it works on Extreme but not GH injector let us know

**Comment by Mauwiii** [comment] 2020-07-02 06:48
Hey,
so i had the same issue but I couldnt inject with the GH injector but with extreme i could
Kind regards

**Comment by GH-Rake** [comment] 2020-07-02 16:24
@Mauwii can you share the source code?  We can try to find the cause of the problem and fix it in the next version

**Comment by Mauwiii** [comment] 2020-07-02 16:44
Yeh sure.
I uploaded it in a repository.
https://github.com/Mauwiii/sourcecode

**Comment by kevinjpetersen** [comment] 2020-07-15 00:13
I can confirm this is happening to me as well. I'm simply injecting a generated .dll using the Unreal Engine SDK Generator (https://github.com/polivilas/UnrealEngineSDKGenerator). 

Injection works fine with Extreme Injector however.

**Comment by GH-Rake** [comment] 2020-08-03 19:25
Some time this year the new version of the injector will be released, we'll wait until then because it will probably be fixed in the new version

**Comment by AlexGFX** [comment] 2020-12-27 00:06
This is happening to me with the first internal hack. I tried versions 3.3, 4.0, 4.1, the same error.

**Comment by GH-Rake** [comment] 2020-12-27 01:41
> This is happening to me with the first internal hack. I tried versions 3.3, 4.0, 4.1, the same error.

if it's happening with all 3 versions, then the problem is most likely with your DLL or with your computer.

Try it again with 4.1, then post the COMPLETE error log here, the one in the log text file
If possible provide the DLL or VS project as well

**Comment by GH-Rake** [comment] 2020-12-27 01:47
I am closing all issues, all bug reports need be completed on the forum from now on

**Closed by GH-Rake** 2020-12-27 01:47 UTC
